---
- name: My Test Playbook
  hosts: all
  become: yes
  tasks:
  - name: Install httpd package
    yum:
     name: httpd
     state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: Install apache2 package
    apt:
      name: apache2
      state: installed
    when: ansible_os_family == "Debian"

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
  
  - name: copy my index file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0666
